version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - yavorfingarov

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    assignees:
      - yavorfingarov
    groups:
      prod:
        dependency-type: production
      dev:
        dependency-type: development
