name: CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

env:
  DENO_VERSION: v2.x
  CLOUDFLARE_PROJECT: fmgeek
  CLOUDFLARE_BRANCH: ${{ github.event_name == 'push' && 'main' || 'test' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Install packages
        run: deno task install

      - name: Check
        run: deno task check

      - name: Format
        run: deno task format

      - name: Lint
        run: deno task lint

      - name: Test
        run: deno task test

      - name: Build
        run: deno task build

      - name: Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: deno task deploy ./dist/ --project-name=${{ env.CLOUDFLARE_PROJECT }} --branch=${{ env.CLOUDFLARE_BRANCH }} --commit-dirty=true
