name: CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_VERSION: 20
  CLOUDFLARE_PROJECT_NAME: fmgeek

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install packages
        run: npm install

      - name: Check style
        run: npm run style:check

      - name: Lint
        run: npm run lint:check

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Publish to Cloudflare Pages
        if: ${{ github.event_name == 'push' }}
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.CLOUDFLARE_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          directory: ./dist
