name: CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

env:
  DENO_VERSION: v2.x
  CLOUDFLARE_PROJECT: fmgeek
  CLOUDFLARE_BRANCH: ${{ github.event_name == 'push' && 'main' || 'test' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Set up Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Install packages
        run: deno task install

      - name: Check
        run: deno task check

      - name: Format
        run: deno task format

      - name: Lint
        run: deno task lint

      - name: Test
        run: deno task test

      - name: Build
        run: deno task build

      - name: Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: deno task deploy ./dist/ --project-name=${{ env.CLOUDFLARE_PROJECT }} --branch=${{ env.CLOUDFLARE_BRANCH }} --commit-dirty=true
