name: Monitor

on:
  schedule:
    - cron: 30 9 * * 1

permissions:
  contents: read

env:
  NODE_VERSION: 22

jobs:
  test-stations:
    name: Test stations
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install packages
        run: npm ci

      - name: Test stations
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 600
          command: npm run test:stations
